# Generated by Django 5.0 on 2024-01-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activityname', models.CharField(max_length=100)),
                ('activityinfo', models.CharField(max_length=255)),
                ('activityspot', models.CharField(max_length=255)),
            ],
        ),
    ]
