# Generated by Django 5.0 on 2024-01-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_activity_activityimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activityimage',
            field=models.ImageField(null=True, upload_to='activities/img'),
        ),
    ]
