# Generated by Django 5.0 on 2024-01-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_alter_activity_activityimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activityimage',
            field=models.ImageField(default='', upload_to='static/image'),
        ),
    ]
