# Generated by Django 5.0 on 2024-01-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_alter_activity_activityimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activityimage',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
