# Generated by Django 5.0 on 2023-12-26 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelspots', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Travelspots',
            new_name='Travelspot',
        ),
    ]
