# Generated by Django 5.0 on 2024-01-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelspots', '0002_rename_travelspots_travelspot'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='travelspot',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='travelspot',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='travelspot_photos/'),
        ),
        migrations.AddField(
            model_name='travelspot',
            name='info',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='travelspot',
            name='link',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
