# Generated by Django 5.0 on 2024-01-06 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelspots', '0003_city_travelspot_address_travelspot_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelspot',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='travelspots', to='travelspots.city'),
        ),
    ]
