# Generated by Django 5.0 on 2024-01-06 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelspots', '0004_travelspot_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hname', models.CharField(max_length=255)),
                ('hinfo', models.CharField(max_length=255, null=True)),
                ('hcity', models.CharField(max_length=255, null=True)),
                ('haddress', models.CharField(max_length=100, null=True)),
                ('hlink', models.CharField(max_length=100, null=True)),
                ('himage', models.ImageField(blank=True, null=True, upload_to='travelspot_photos/')),
            ],
        ),
    ]
