# Generated by Django 5.0 on 2024-01-06 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='article',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='place',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='title',
            new_name='projectName',
        ),
    ]
